### PR TITLE
make opAssign from Optional work with non-copyable value

### PR DESCRIPTION
**Pull request by skoppe**

### CODE REVIEW

**Comment by skoppe** [comment]
Ohh, I should really make a unittest. Will do later

**Comment by aliak00** [comment]
Ok I may have prematurely merged this 😂I'm wondering now if it's the right thing to do.
If A!T is a type where T is not copyable, then I don't think A!T.opAssign should work 🤔 

T = T doesn't work then why should A!T = A!T?

**Comment by aliak00** [comment]
Also:
```
auto a = some(T())
auto b = a; // a move without warning
b = a; // what's happening here?
```

**Comment by skoppe** [comment]
The use case is this:

```D
struct S {
  @disabled this(this);
}

Optional!S fun() {...}

struct Foo {
  Optional!S field;
  auto bar() {
    field = fun();
  }
}
```

I cannot do `field = fun().move()`;

I can work around it with:

```D
import std.algorithm : move;
auto r = fun();
r.move(field);
```

**Comment by skoppe** [comment]
> ```D
> auto a = some(T())
> auto b = a; // a move without warning
> b = a; // what's happening here?
> ```

Now both are empty. 

It happens with normal values as well. Of course having the move be implicit isn't great.

**Comment by skoppe** [comment]
It is pretty controversial I agree. I am ok with you reverting this.

**Comment by aliak00** [comment]
Cool. Will do! 👍

**Comment by aliak00** [comment]
I'm considering adding this instead for your use-case.
```
struct Optional {
    static if (isMutable!T) {
        auto move(ref Optional!T target) {
            import std.algorithm: move;
            return move(this, target);
        }
    }
}
```


And also what the impact of this would be:
```
void opAssign(U : T)(auto ref Optional!U lhs) if (isMutable!T && isAssignable!(T, U))  {
        static if (__traits(isRef, lhs)) {
            this._value = lhs._value;
        } else {
            import std.algorithm: move;
            move(lhs._value, this._value);
        }
        this.defined = lhs.defined;
    }
```

**Comment by skoppe** [comment]
First one is a solid solution. Second one is interesting. It might solve it.

A good approach would be to spell out all the combinations of construction/assignment with non-copyable/copyable under ref/lval/rval and see if all works as desired.

In general I think being explicit when things are moved is a good thing.

**Comment by aliak00** [comment]
@skoppe I went with the `isRef` approach for now. From what I understand d should move things anyway, but for some reason it doesn't work when you define a custom opAssign, even though it does exactly the same thing. So moving an lvalue should be safe as far as I know.

pushed a release as well now.

**Comment by skoppe** [comment]
Nice! Thanks.

**Pull request merged**
